### ISSUE TITLE
Changing the UI

### ISSUE THREAD

**Issue by alfaqi** [0xBcamp/Sept23_Apprenticeship_Certification#14]
I'm working on UI
my goals are
1. changing `web3uikit` library to `NextUI` or `MUI` library.
2. adding some motions
3. adding Home page (more creative)

**Comment by thanvinhbaohoang** [comment]
@alfaqi Try looking into `shadcn`. It is a pretty dope Tailwind Library that I am looking into trying out too

**Comment by alfaqi** [comment]
I'm checking `Shadcn` UI

**Comment by alfaqi** [comment]
@thanvinhbaohoang 
It's so cool,
do I have to change the UI or it's ok with MUI

**Comment by alfaqi** [comment]
[newLook](https://github.com/0xBcamp/Sept23_Apprenticeship_Certification/tree/newLook)
Done
