### ISSUE TITLE
[User Profile] Make `SearchBar` Able to search for any user profile 

### ISSUE THREAD

**Issue by thanvinhbaohoang** [0xBcamp/Sept23_Apprenticeship_Certification#22]
Fetch User Profile from `SearchBar`

**Comment by thanvinhbaohoang** [comment]
`BNS Name` Search is working but regular Wallet Address search is not

**Comment by alfaqi** [comment]
I fixed that,
Please check that again and let me know if it's not working

**Comment by razawired** [comment]
Yeah it works:
![image](https://github.com/0xBcamp/Sept23_Apprenticeship_Certification/assets/32830427/d21a2941-1e3c-4853-bb9e-ddfa4cd3050f)


Closing the issue now
