### ISSUE TITLE
SBT is transferable to other accounts with Currect schema and contract

### ISSUE THREAD

**Issue by razawired** [0xBcamp/Sept23_Apprenticeship_Certification#38]
**Description:**

There are two major concerns that need to be addressed:

1. **SBT Token Transfer Issue:** Once the SBT token is minted to a specific wallet, it seems to be transferrable to any other wallet. This behavior is unexpected and problematic. 
   - **Proposed Solution:** I will be working on creating a certificate attestation contract. This contract will mint through a schema and will incorporate the necessary features, including the ability to send the SBT through a single transaction on onattest through schema

2. **Schema Overlap Bug:** There seems to be a bug where the schema is overlapping, causing the import of previously minted tokens by the same address with the same ID. This behavior is unintended and could lead to potential issues in token management.
   - **Expected Behavior:** Every minting action should produce a unique token ID for a given address. No two tokens should have the same ID for the same address.
   - **Current Behavior:** Tokens minted by the same address seem to inherit the same ID from previous minting actions.

I will be assigning myself to this issue and will start working on addressing these concerns promptly.

Here are some screenshots:
![image](https://github.com/0xBcamp/Sept23_Apprenticeship_Certification/assets/32830427/76169e43-2231-4e5a-93cc-288977de3e1e)
![image](https://github.com/0xBcamp/Sept23_Apprenticeship_Certification/assets/32830427/cd1173e1-fb3e-4d99-84ec-3afc88b60ccc)
![image](https://github.com/0xBcamp/Sept23_Apprenticeship_Certification/assets/32830427/41459bdb-d34e-4c05-b0db-e809a48dce61)

**Comment by alfaqi** [comment]
Nice caught 
This function is what we needed to implement
```solidity
function transferFrom(
        address from,
        address to,
        uint256 tokenId
    ) public override {
        require(
            from == address(0),
            "This a Soulbound token. It cannot be transferred."
        );
        transferFrom(from, to, tokenId);
    }
```
